// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum3.proto

#include "Enum3.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace PROTOCOL {
}  // namespace PROTOCOL
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_Enum3_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Enum3_2eproto = nullptr;
const uint32_t TableStruct_Enum3_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum3_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013Enum3.proto\022\010PROTOCOL*%\n\nACTOR_TYPE\022\n\n"
  "\006PLAYER\020\000\022\013\n\007MONSTER\020\001*\"\n\nATTACKTYPE\022\t\n\005"
  "BASIC\020\000\022\t\n\005SKILL\020\001b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Enum3_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum3_2eproto = {
  false, false, 106, descriptor_table_protodef_Enum3_2eproto, "Enum3.proto", 
  &descriptor_table_Enum3_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_Enum3_2eproto::offsets,
  nullptr, file_level_enum_descriptors_Enum3_2eproto, file_level_service_descriptors_Enum3_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Enum3_2eproto_getter() {
  return &descriptor_table_Enum3_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Enum3_2eproto(&descriptor_table_Enum3_2eproto);
namespace PROTOCOL {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ACTOR_TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum3_2eproto);
  return file_level_enum_descriptors_Enum3_2eproto[0];
}
bool ACTOR_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ATTACKTYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum3_2eproto);
  return file_level_enum_descriptors_Enum3_2eproto[1];
}
bool ATTACKTYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace PROTOCOL
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
