// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum3.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum3_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum3_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum3_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum3_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum3_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace PROTOCOL {

enum ACTOR_TYPE : int {
  PLAYER = 0,
  MONSTER = 1,
  ACTOR_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ACTOR_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ACTOR_TYPE_IsValid(int value);
constexpr ACTOR_TYPE ACTOR_TYPE_MIN = PLAYER;
constexpr ACTOR_TYPE ACTOR_TYPE_MAX = MONSTER;
constexpr int ACTOR_TYPE_ARRAYSIZE = ACTOR_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ACTOR_TYPE_descriptor();
template<typename T>
inline const std::string& ACTOR_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ACTOR_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ACTOR_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ACTOR_TYPE_descriptor(), enum_t_value);
}
inline bool ACTOR_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ACTOR_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ACTOR_TYPE>(
    ACTOR_TYPE_descriptor(), name, value);
}
enum ATTACKTYPE : int {
  BASIC = 0,
  SKILL = 1,
  ATTACKTYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ATTACKTYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ATTACKTYPE_IsValid(int value);
constexpr ATTACKTYPE ATTACKTYPE_MIN = BASIC;
constexpr ATTACKTYPE ATTACKTYPE_MAX = SKILL;
constexpr int ATTACKTYPE_ARRAYSIZE = ATTACKTYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ATTACKTYPE_descriptor();
template<typename T>
inline const std::string& ATTACKTYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ATTACKTYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ATTACKTYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ATTACKTYPE_descriptor(), enum_t_value);
}
inline bool ATTACKTYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ATTACKTYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ATTACKTYPE>(
    ATTACKTYPE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace PROTOCOL

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PROTOCOL::ACTOR_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PROTOCOL::ACTOR_TYPE>() {
  return ::PROTOCOL::ACTOR_TYPE_descriptor();
}
template <> struct is_proto_enum< ::PROTOCOL::ATTACKTYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PROTOCOL::ATTACKTYPE>() {
  return ::PROTOCOL::ATTACKTYPE_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum3_2eproto
